name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Left Part
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_left.*
          template: classic
          repositories_forks: yes
          base_indepth: yes
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_skipped: dotfiles, hexo-blog shejialuo.github.io
          plugin_rss: yes
          plugin_rss_source: https://luolibrary.com/atom.xml
          plugin_rss_limit: 4
          plugin_anilist: yes
          plugin_anilist_user: shejialuo
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1

      - name: Right Part
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.*
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_activity: yes

